#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.6.3 on Sat Feb 09 13:04:12 2008

import wx

# begin wxGlade: extracode
# end wxGlade



class doubleThresholdFLTFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: doubleThresholdFLTFrame.__init__
        kwds["style"] = wx.CAPTION|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER
        wx.Frame.__init__(self, *args, **kwds)
        self.viewFramePanel = wx.Panel(self, -1)
        self.label_1 = wx.StaticText(self.viewFramePanel, -1, "Lower threshold")
        self.lowerThresholdTextId = wx.NewId()
        self.lowerThresholdText = wx.TextCtrl(self.viewFramePanel, self.lowerThresholdTextId, "", style=wx.TE_PROCESS_ENTER)
        self.label_2 = wx.StaticText(self.viewFramePanel, -1, "Upper threshold")
        self.upperThresholdTextId = wx.NewId()
        self.upperThresholdText = wx.TextCtrl(self.viewFramePanel, self.upperThresholdTextId, "", style=wx.TE_PROCESS_ENTER)
        self.replaceInCheckBox = wx.CheckBox(self.viewFramePanel, -1, "Replace IN values with:")
        self.replaceInText = wx.TextCtrl(self.viewFramePanel, -1, "")
        self.replaceOutCheckBox = wx.CheckBox(self.viewFramePanel, -1, "Replace OUT values with:")
        self.replaceOutText = wx.TextCtrl(self.viewFramePanel, -1, "")
        self.label_3 = wx.StaticText(self.viewFramePanel, -1, "Output data type")
        self.outputDataTypeChoice = wx.Choice(self.viewFramePanel, -1, choices=["choice 1"])

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: doubleThresholdFLTFrame.__set_properties
        self.SetTitle("Double Threshold Filter")
        self.replaceInCheckBox.SetValue(1)
        self.replaceOutCheckBox.SetValue(1)
        self.outputDataTypeChoice.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: doubleThresholdFLTFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2 = wx.FlexGridSizer(2, 2, 4, 4)
        grid_sizer_1 = wx.FlexGridSizer(2, 2, 4, 4)
        grid_sizer_1.Add(self.label_1, 0, wx.LEFT|wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 2)
        grid_sizer_1.Add(self.lowerThresholdText, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.label_2, 0, wx.LEFT|wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 2)
        grid_sizer_1.Add(self.upperThresholdText, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.AddGrowableCol(1)
        sizer_5.Add(grid_sizer_1, 1, wx.ALL|wx.EXPAND, 7)
        grid_sizer_2.Add(self.replaceInCheckBox, 0, 0, 0)
        grid_sizer_2.Add(self.replaceInText, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.replaceOutCheckBox, 0, 0, 0)
        grid_sizer_2.Add(self.replaceOutText, 0, wx.EXPAND, 0)
        grid_sizer_2.AddGrowableCol(1)
        sizer_5.Add(grid_sizer_2, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 7)
        sizer_3.Add(self.label_3, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 3)
        sizer_3.Add(self.outputDataTypeChoice, 1, 0, 0)
        sizer_5.Add(sizer_3, 0, wx.ALL|wx.EXPAND, 7)
        self.viewFramePanel.SetSizer(sizer_5)
        sizer_1.Add(self.viewFramePanel, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class doubleThresholdFLTFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = doubleThresholdFLTFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
