#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Tue May 13 18:30:28 2008

import wx
import wx.grid

# begin wxGlade: extracode
# end wxGlade



class EditMedicalMetaDataViewFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: EditMedicalMetaDataViewFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.view_frame_panel = wx.Panel(self, -1)
        self.prop_grid = wx.grid.Grid(self.view_frame_panel, -1, size=(1, 1))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: EditMedicalMetaDataViewFrame.__set_properties
        self.SetTitle("frame_2")
        self.prop_grid.CreateGrid(10, 2)
        self.prop_grid.SetRowLabelSize(0)
        self.prop_grid.EnableDragColSize(0)
        self.prop_grid.SetColLabelValue(0, "Tag")
        self.prop_grid.SetColLabelValue(1, "Value")
        self.prop_grid.SetMinSize((165, 210))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: EditMedicalMetaDataViewFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.prop_grid, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 1, wx.ALL|wx.EXPAND, 7)
        self.view_frame_panel.SetSizer(sizer_1)
        sizer_2.Add(self.view_frame_panel, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

# end of class EditMedicalMetaDataViewFrame


class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

# end of class MyFrame1


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_2 = MyFrame1(None, -1, "")
    app.SetTopWindow(frame_2)
    frame_2.Show()
    app.MainLoop()
