#!/usr/bin/env python
# generated by wxGlade 0.3.1 on Sun Sep 21 18:00:31 2003

from wxPython.wx import *

class imageGaussianSmoothViewFrame(wxFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: imageGaussianSmoothViewFrame.__init__
        kwds["style"] = wxDEFAULT_FRAME_STYLE
        wxFrame.__init__(self, *args, **kwds)
        self.viewFramePanel = wxPanel(self, -1)
        self.label_4 = wxStaticText(self.viewFramePanel, -1, "Standard Deviations (pixels)")
        self.stdTextCtrl = wxTextCtrl(self.viewFramePanel, -1, "")
        self.label_5 = wxStaticText(self.viewFramePanel, -1, "Radius Cutoff (pixels)")
        self.radiusCutoffTextCtrl = wxTextCtrl(self.viewFramePanel, -1, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: imageGaussianSmoothViewFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: imageGaussianSmoothViewFrame.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_2 = wxBoxSizer(wxVERTICAL)
        sizer_3 = wxBoxSizer(wxVERTICAL)
        grid_sizer_3 = wxFlexGridSizer(2, 2, 4, 3)
        grid_sizer_3.Add(self.label_4, 0, wxALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.stdTextCtrl, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.label_5, 0, wxALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.radiusCutoffTextCtrl, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.AddGrowableCol(1)
        sizer_3.Add(grid_sizer_3, 1, wxEXPAND, 0)
        sizer_2.Add(sizer_3, 1, wxALL|wxEXPAND, 7)
        self.viewFramePanel.SetAutoLayout(1)
        self.viewFramePanel.SetSizer(sizer_2)
        sizer_2.Fit(self.viewFramePanel)
        sizer_2.SetSizeHints(self.viewFramePanel)
        sizer_1.Add(self.viewFramePanel, 1, wxEXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class imageGaussianSmoothViewFrame


class MyFrame(wxFrame):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

# end of class MyFrame


