#!/usr/bin/env python
# generated by wxGlade 0.3.1 on Thu Oct 16 11:06:42 2003

from wxPython.wx import *

class resampleImageViewFrame(wxFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: resampleImageViewFrame.__init__
        kwds["style"] = wxDEFAULT_FRAME_STYLE
        wxFrame.__init__(self, *args, **kwds)
        self.viewFramePanel = wxPanel(self, -1)
        self.label_1 = wxStaticText(self.viewFramePanel, -1, "Interpolation type:")
        self.interpolationTypeChoice = wxChoice(self.viewFramePanel, -1, choices=["Nearest Neighbour", "Linear", "Cubic"])
        self.label_2 = wxStaticText(self.viewFramePanel, -1, "x,y,z Magnification:")
        self.magFactorXText = wxTextCtrl(self.viewFramePanel, -1, "")
        self.label_3 = wxStaticText(self.viewFramePanel, -1, ",")
        self.magFactorYText = wxTextCtrl(self.viewFramePanel, -1, "")
        self.label_4 = wxStaticText(self.viewFramePanel, -1, ",")
        self.magFactorZText = wxTextCtrl(self.viewFramePanel, -1, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: resampleImageViewFrame.__set_properties
        self.SetTitle("frame_1")
        self.interpolationTypeChoice.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: resampleImageViewFrame.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_2 = wxBoxSizer(wxVERTICAL)
        sizer_3 = wxBoxSizer(wxVERTICAL)
        sizer_5 = wxBoxSizer(wxHORIZONTAL)
        sizer_4 = wxBoxSizer(wxHORIZONTAL)
        sizer_4.Add(self.label_1, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 3)
        sizer_4.Add(self.interpolationTypeChoice, 1, wxALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(sizer_4, 1, wxBOTTOM|wxEXPAND, 7)
        sizer_5.Add(self.label_2, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 3)
        sizer_5.Add(self.magFactorXText, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 3)
        sizer_5.Add(self.label_3, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 3)
        sizer_5.Add(self.magFactorYText, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 3)
        sizer_5.Add(self.label_4, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 3)
        sizer_5.Add(self.magFactorZText, 0, wxALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(sizer_5, 1, wxEXPAND, 0)
        sizer_2.Add(sizer_3, 1, wxALL|wxEXPAND, 7)
        self.viewFramePanel.SetAutoLayout(1)
        self.viewFramePanel.SetSizer(sizer_2)
        sizer_2.Fit(self.viewFramePanel)
        sizer_2.SetSizeHints(self.viewFramePanel)
        sizer_1.Add(self.viewFramePanel, 1, wxEXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class resampleImageViewFrame


class MyFrame(wxFrame):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

# end of class MyFrame


