#!/usr/bin/env python
# generated by wxGlade 0.2.2 on Sun May 04 02:42:15 2003

from wxPython.wx import *

class shellSplatSimpleFLTViewFrame(wxFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: shellSplatSimpleFLTViewFrame.__init__
        kwds["style"] = wxCAPTION|wxMINIMIZE_BOX|wxMAXIMIZE_BOX|wxSYSTEM_MENU|wxRESIZE_BORDER
        wxFrame.__init__(self, *args, **kwds)
        self.viewFramePanel = wxPanel(self, -1)
        self.label_8_copy_1_copy = wxStaticText(self.viewFramePanel, -1, "Threshold")
        self.thresholdText = wxTextCtrl(self.viewFramePanel, -1, "")
        self.colourButtonId  =  wxNewId()
        self.colourButton = wxButton(self.viewFramePanel, self.colourButtonId , "Colour")
        self.colourText = wxTextCtrl(self.viewFramePanel, -1, "")
        self.label_1_copy = wxStaticText(self.viewFramePanel, -1, "Rendering Mode")
        self.renderingModeChoice = wxChoice(self.viewFramePanel, -1, choices=["High Quality", "Faster", "Fastest"])
        self.gradientImageIsGradientCheckBox = wxCheckBox(self.viewFramePanel, -1, "Gradient Image is Gradient")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: shellSplatSimpleFLTViewFrame.__set_properties
        self.SetTitle("shellSplatSimpleFLT View")
        self.renderingModeChoice.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: shellSplatSimpleFLTViewFrame.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_5 = wxBoxSizer(wxVERTICAL)
        sizer_4 = wxBoxSizer(wxVERTICAL)
        sizer_2 = wxBoxSizer(wxHORIZONTAL)
        sizer_3 = wxBoxSizer(wxHORIZONTAL)
        sizer_3.Add(self.label_8_copy_1_copy, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 3)
        sizer_3.Add(self.thresholdText, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 7)
        sizer_3.Add(self.colourButton, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 3)
        sizer_3.Add(self.colourText, 1, wxALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(sizer_3, 1, wxBOTTOM|wxEXPAND, 7)
        sizer_2.Add(self.label_1_copy, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 3)
        sizer_2.Add(self.renderingModeChoice, 1, wxLEFT|wxRIGHT|wxALIGN_CENTER_VERTICAL, 2)
        sizer_4.Add(sizer_2, 1, wxBOTTOM|wxEXPAND, 7)
        sizer_4.Add(self.gradientImageIsGradientCheckBox, 0, 0, 0)
        sizer_5.Add(sizer_4, 1, wxALL|wxEXPAND, 7)
        self.viewFramePanel.SetAutoLayout(1)
        self.viewFramePanel.SetSizer(sizer_5)
        sizer_5.Fit(self.viewFramePanel)
        sizer_5.SetSizeHints(self.viewFramePanel)
        sizer_1.Add(self.viewFramePanel, 1, wxEXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class shellSplatSimpleFLTViewFrame


