#!/usr/bin/env python
# generated by wxGlade 0.2.2 on Tue May 13 11:44:31 2003

from wxPython.wx import *

class wsMeshSmoothFLTViewFrame(wxFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wsMeshSmoothFLTViewFrame.__init__
        kwds["style"] = wxDEFAULT_FRAME_STYLE
        wxFrame.__init__(self, *args, **kwds)
        self.viewFramePanel = wxPanel(self, -1)
        self.label_1 = wxStaticText(self.viewFramePanel, -1, "Smoothing iterations")
        self.smoothingIterationsText = wxTextCtrl(self.viewFramePanel, -1, "")
        self.label_2 = wxStaticText(self.viewFramePanel, -1, "Pass band (0 - 2, default 0.1)")
        self.passBandText = wxTextCtrl(self.viewFramePanel, -1, "")
        self.featureEdgeSmoothingCheckBox = wxCheckBox(self.viewFramePanel, -1, "Feature edge smoothing")
        self.boundarySmoothingCheckBox = wxCheckBox(self.viewFramePanel, -1, "Boundary smoothing")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wsMeshSmoothFLTViewFrame.__set_properties
        self.SetTitle("Windowed sinc mesh smoother")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wsMeshSmoothFLTViewFrame.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_2 = wxBoxSizer(wxVERTICAL)
        grid_sizer_1 = wxFlexGridSizer(2, 2, 5, 5)
        grid_sizer_1.Add(self.label_1, 0, wxALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.smoothingIterationsText, 0, wxALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.label_2, 0, wxALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.passBandText, 0, wxALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.AddGrowableCol(1)
        sizer_2.Add(grid_sizer_1, 1, wxALL, 5)
        sizer_2.Add(self.featureEdgeSmoothingCheckBox, 0, wxALL|wxALIGN_CENTER_VERTICAL, 5)
        sizer_2.Add(self.boundarySmoothingCheckBox, 0, wxALL|wxALIGN_CENTER_VERTICAL, 5)
        self.viewFramePanel.SetAutoLayout(1)
        self.viewFramePanel.SetSizer(sizer_2)
        sizer_2.Fit(self.viewFramePanel)
        sizer_2.SetSizeHints(self.viewFramePanel)
        sizer_1.Add(self.viewFramePanel, 1, wxEXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class wsMeshSmoothFLTViewFrame



