#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Mon Apr 27 12:53:31 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class CoMedIControlsFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CoMedIControlsFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.main_panel = wx.Panel(self, -1)
        self.notebook = wx.Notebook(self.main_panel, -1, style=0)
        self.sizer_4_staticbox = wx.StaticBox(self.main_panel, -1, "General")
        self.sync_checkbox = wx.CheckBox(self.main_panel, -1, "Synchronise Views")
        self.label_1 = wx.StaticText(self.main_panel, -1, "Current 3D cursor")
        self.cursor_text = wx.TextCtrl(self.main_panel, -1, "")
        self.notebook_pane_ssl = wx.Panel(self.notebook, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CoMedIControlsFrame.__set_properties
        self.SetTitle("frame_1")
        self.sync_checkbox.SetValue(1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CoMedIControlsFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.sync_checkbox, 0, wx.TOP|wx.BOTTOM, 7)
        sizer_5.Add(self.label_1, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 4)
        sizer_5.Add(self.cursor_text, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(sizer_5, 0, wx.BOTTOM|wx.EXPAND, 7)
        sizer_3.Add(sizer_4, 0, wx.EXPAND, 0)
        self.notebook.AddPage(self.notebook_pane_ssl, "Single Structure Landmarks")
        sizer_3.Add(self.notebook, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, wx.ALL|wx.EXPAND, 7)
        self.main_panel.SetSizer(sizer_2)
        sizer_1.Add(self.main_panel, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class CoMedIControlsFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = CoMedIControlsFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
