#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Wed Sep 10 21:49:20 2008

import wx

# begin wxGlade: extracode
# import the RWI (why does this line appear twice?)
from vtk.wx.wxVTKRenderWindowInteractor import wxVTKRenderWindowInteractor


# import the RWI (why does this line appear twice?)
from vtk.wx.wxVTKRenderWindowInteractor import wxVTKRenderWindowInteractor


# end wxGlade



class FilesPanelFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FilesPanelFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.files_panel = wx.Panel(self, -1)
        self.dirs_files_tc = wx.TextCtrl(self.files_panel, -1, "", style=wx.TE_NOHIDESEL)
        self.ad_button = wx.Button(self.files_panel, -1, "Add Dirs")
        self.af_button = wx.Button(self.files_panel, -1, "Add Files")
        self.scan_button = wx.Button(self.files_panel, -1, "Scan")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FilesPanelFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FilesPanelFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.dirs_files_tc, 1, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 7)
        sizer_3.Add(self.ad_button, 0, wx.RIGHT, 4)
        sizer_3.Add(self.af_button, 0, wx.RIGHT, 4)
        sizer_3.Add(self.scan_button, 0, 0, 0)
        sizer_2.Add(sizer_3, 0, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 7)
        self.files_panel.SetSizer(sizer_2)
        sizer_1.Add(self.files_panel, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class FilesPanelFrame


class ImagePanelFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ImagePanelFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.image_panel = wx.Panel(self, -1)
        self.sizer_6_staticbox = wx.StaticBox(self.image_panel, -1, "Image Viewer Controls")
        self.rwi = wxVTKRenderWindowInteractor(self.image_panel, -1)
        self.lock_pz_cb = wx.CheckBox(self.image_panel, -1, "Lock PAN / ZOOM")
        self.lock_wl_cb = wx.CheckBox(self.image_panel, -1, "Lock WINDOW / LEVEL")
        self.reset_b = wx.Button(self.image_panel, -1, "Reset Image")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ImagePanelFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ImagePanelFrame.__do_layout
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.StaticBoxSizer(self.sizer_6_staticbox, wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy.Add(self.rwi, 1, wx.EXPAND, 0)
        sizer_7.Add(self.lock_pz_cb, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 7)
        sizer_7.Add(self.lock_wl_cb, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 4)
        sizer_7.Add(self.reset_b, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(sizer_7, 1, 0, 0)
        sizer_5_copy.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_5.Add(sizer_5_copy, 1, wx.ALL|wx.EXPAND, 7)
        self.image_panel.SetSizer(sizer_5)
        sizer_4.Add(self.image_panel, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_4)
        sizer_4.Fit(self)
        self.Layout()
        # end wxGlade

# end of class ImagePanelFrame


class ImageFilesFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ImageFilesFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.files_panel = wx.Panel(self, -1)
        self.files_lc = wx.ListCtrl(self.files_panel, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.ipp_sort_button = wx.Button(self.files_panel, -1, "IPP Sort")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ImageFilesFrame.__set_properties
        self.SetTitle("frame_2")
        self.ipp_sort_button.SetToolTipString("Sort the current image files according to the Image Position Patient.")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ImageFilesFrame.__do_layout
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9.Add(self.files_lc, 1, wx.EXPAND, 0)
        sizer_10.Add(self.ipp_sort_button, 0, 0, 0)
        sizer_9.Add(sizer_10, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.EXPAND, 7)
        self.files_panel.SetSizer(sizer_9)
        sizer_8.Add(self.files_panel, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_8)
        sizer_8.Fit(self)
        self.Layout()
        # end wxGlade

# end of class ImageFilesFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    files_panel_frame = FilesPanelFrame(None, -1, "")
    app.SetTopWindow(files_panel_frame)
    files_panel_frame.Show()
    app.MainLoop()
