#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sun Mar 16 22:57:49 2008

import wx

# begin wxGlade: extracode
# end wxGlade



class FilesPanelFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FilesPanelFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.files_panel = wx.Panel(self, -1)
        self.dirs_files_lb = wx.ListBox(self.files_panel, -1, choices=[], style=wx.LB_EXTENDED|wx.LB_HSCROLL|wx.LB_NEEDED_SB)
        self.ad_button = wx.Button(self.files_panel, -1, "Add Dirs")
        self.af_button = wx.Button(self.files_panel, -1, "Add Files")
        self.r_button = wx.Button(self.files_panel, -1, "Remove")
        self.scan_button = wx.Button(self.files_panel, -1, "Scan")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FilesPanelFrame.__set_properties
        self.SetTitle("frame_1")
        self.dirs_files_lb.SetMinSize((267, 25))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FilesPanelFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.dirs_files_lb, 1, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 7)
        sizer_3.Add(self.ad_button, 0, wx.RIGHT, 4)
        sizer_3.Add(self.af_button, 0, wx.RIGHT, 4)
        sizer_3.Add(self.r_button, 0, wx.RIGHT, 4)
        sizer_3.Add(self.scan_button, 0, 0, 0)
        sizer_2.Add(sizer_3, 0, wx.RIGHT|wx.TOP|wx.BOTTOM, 7)
        self.files_panel.SetSizer(sizer_2)
        sizer_1.Add(self.files_panel, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class FilesPanelFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    files_panel_frame = FilesPanelFrame(None, -1, "")
    app.SetTopWindow(files_panel_frame)
    files_panel_frame.Show()
    app.MainLoop()
