#!/usr/bin/env python
# generated by wxGlade 0.3.3 on Mon Aug 16 00:22:23 2004

import wx

# with the very ugly two lines below, make sure x capture is not used
# this should rather be an ivar of the wxVTKRenderWindowInteractor!
import vtk.wx.wxVTKRenderWindowInteractor
vtk.wx.wxVTKRenderWindowInteractor.WX_USE_X_CAPTURE = 0
from vtk.wx.wxVTKRenderWindowInteractor import wxVTKRenderWindowInteractor

class viewFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: viewFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.rwi = wxVTKRenderWindowInteractor(self.panel_1, -1)
        self.addWidgetButton = wx.Button(self.panel_1, -1, "Add widget")
        self.removeWidgetButton = wx.Button(self.panel_1, -1, "Remove widget")
        self.addNodeButton = wx.Button(self.panel_1, -1, "Add node")
        self.removeNodeButton = wx.Button(self.panel_1, -1, "Remove node")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: viewFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: viewFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.rwi, 1, wx.EXPAND, 0)
        sizer_4.Add((0, 320), 0, 0, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_5.Add(self.addWidgetButton, 0, wx.RIGHT, 7)
        sizer_5.Add(self.removeWidgetButton, 0, wx.RIGHT, 7)
        sizer_5.Add(self.addNodeButton, 0, wx.RIGHT, 7)
        sizer_5.Add(self.removeNodeButton, 0, 0, 0)
        sizer_3.Add(sizer_5, 0, wx.TOP|wx.EXPAND, 7)
        sizer_2.Add(sizer_3, 1, wx.ALL|wx.EXPAND, 7)
        self.panel_1.SetAutoLayout(1)
        self.panel_1.SetSizer(sizer_2)
        sizer_2.Fit(self.panel_1)
        sizer_2.SetSizeHints(self.panel_1)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class viewFrame


