#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.3.4pre on Tue Aug  3 16:35:38 2004

import wx
from external import wxPyPlot

class histogram1DFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: histogram1DFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.viewFramePanel = wx.Panel(self, -1)
        self.plotCanvas = wxPyPlot.PlotCanvas(self.viewFramePanel, -1)
        self.label_1 = wx.StaticText(self.viewFramePanel, -1, "Number of bins")
        self.numBinsSpinCtrl = wx.SpinCtrl(self.viewFramePanel, -1, "", min=1, max=999999999)
        self.label_2 = wx.StaticText(self.viewFramePanel, -1, "Minimum value")
        self.minValueText = wx.TextCtrl(self.viewFramePanel, -1, "")
        self.label_3 = wx.StaticText(self.viewFramePanel, -1, "Maximum value")
        self.maxValueText = wx.TextCtrl(self.viewFramePanel, -1, "")
        self.autoRangeButton = wx.Button(self.viewFramePanel, -1, "Auto range")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: histogram1DFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: histogram1DFrame.__do_layout
        topLevelSizer = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.StaticBoxSizer(wx.StaticBox(self.viewFramePanel, -1, ""), wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7.Add(self.plotCanvas, 1, wx.EXPAND, 0)
        sizer_7.Add((0, 300), 0, 0, 0)
        sizer_3.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_5.Add(self.label_1, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 4)
        sizer_5.Add(self.numBinsSpinCtrl, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(sizer_5, 1, wx.ALL|wx.EXPAND, 7)
        sizer_6.Add(self.label_2, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 4)
        sizer_6.Add(self.minValueText, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 7)
        sizer_6.Add(self.label_3, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 4)
        sizer_6.Add(self.maxValueText, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 7)
        sizer_6.Add(self.autoRangeButton, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(sizer_6, 1, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 7)
        sizer_3.Add(sizer_4, 0, wx.TOP|wx.EXPAND, 7)
        sizer_2.Add(sizer_3, 1, wx.ALL|wx.EXPAND, 7)
        self.viewFramePanel.SetAutoLayout(1)
        self.viewFramePanel.SetSizer(sizer_2)
        sizer_2.Fit(self.viewFramePanel)
        sizer_2.SetSizeHints(self.viewFramePanel)
        topLevelSizer.Add(self.viewFramePanel, 1, wx.EXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(topLevelSizer)
        topLevelSizer.Fit(self)
        topLevelSizer.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class histogram1DFrame


