#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sat Jan 17 21:35:13 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class QuickInfoFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: QuickInfoFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.view_frame_panel = wx.Panel(self, -1)
        self.output_text = wx.TextCtrl(self.view_frame_panel, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_AUTO_URL|wx.TE_LINEWRAP|wx.TE_WORDWRAP)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: QuickInfoFrame.__set_properties
        self.SetTitle("frame_1")
        self.output_text.SetMinSize((100, 34))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: QuickInfoFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.output_text, 1, wx.EXPAND, 0)
        sizer_4.Add((0, 400), 0, 0, 0)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_2.Add((400, 0), 0, 0, 0)
        sizer_3.Add(sizer_2, 1, wx.ALL|wx.EXPAND, 7)
        self.view_frame_panel.SetSizer(sizer_3)
        sizer_1.Add(self.view_frame_panel, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class QuickInfoFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = QuickInfoFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
