#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4 on Sun Apr 02 19:01:15 2006

import wx
from wx.lib.floatcanvas import NavCanvas, FloatCanvas, Resources

class TFEditorFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: TFEditorFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.view_frame_panel = wx.Panel(self, -1)
        self.opacity_static_sizer_staticbox = wx.StaticBox(self.view_frame_panel, -1, "Opacity Transfer Function")
        self.opacity_canvas = NavCanvas.NavCanvas(self.view_frame_panel, -1)
        self.label_1 = wx.StaticText(self.view_frame_panel, -1, "Scalar MIN")
        self.opacity_scalar_min_text = wx.TextCtrl(self.view_frame_panel, -1, "")
        self.label_2 = wx.StaticText(self.view_frame_panel, -1, "MAX")
        self.opacity_scalar_max_text = wx.TextCtrl(self.view_frame_panel, -1, "")
        self.auto_range_button = wx.Button(self.view_frame_panel, -1, "Auto Range")
        self.apply_range_button = wx.Button(self.view_frame_panel, -1, "Apply Range")
        self.introspect_button = wx.Button(self.view_frame_panel, -1, "Introspect")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: TFEditorFrame.__set_properties
        self.SetTitle("frame_2")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: TFEditorFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        opacity_static_sizer = wx.StaticBoxSizer(self.opacity_static_sizer_staticbox, wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add((400, 0), 0, wx.ADJUST_MINSIZE, 0)
        sizer_4.Add(self.opacity_canvas, 1, wx.EXPAND, 0)
        sizer_4.Add((0, 200), 0, wx.ADJUST_MINSIZE, 0)
        opacity_static_sizer.Add(sizer_4, 1, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND, 7)
        sizer_5.Add(self.label_1, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 3)
        sizer_5.Add(self.opacity_scalar_min_text, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 4)
        sizer_5.Add(self.label_2, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 3)
        sizer_5.Add(self.opacity_scalar_max_text, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 7)
        sizer_5.Add(self.auto_range_button, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 4)
        sizer_5.Add(self.apply_range_button, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        opacity_static_sizer.Add(sizer_5, 0, wx.ALL|wx.EXPAND, 7)
        sizer_3.Add(opacity_static_sizer, 1, wx.EXPAND, 7)
        sizer_6.Add(self.introspect_button, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(sizer_6, 0, wx.TOP|wx.ALIGN_RIGHT, 7)
        sizer_2.Add(sizer_3, 1, wx.ALL|wx.EXPAND, 7)
        self.view_frame_panel.SetAutoLayout(True)
        self.view_frame_panel.SetSizer(sizer_2)
        sizer_2.Fit(self.view_frame_panel)
        sizer_2.SetSizeHints(self.view_frame_panel)
        sizer_1.Add(self.view_frame_panel, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class TFEditorFrame


