#!/usr/bin/env python
# generated by wxGlade 0.2.1cvs on Thu Jan 23 17:04:32 2003

from wxPython.wx import *
from wxPython.html import *

class aboutDialog(wxDialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: aboutDialog.__init__
        kwds["style"] = wxDEFAULT_DIALOG_STYLE
        wxDialog.__init__(self, *args, **kwds)
        self.htmlWindow = wxHtmlWindow(self, -1)
        self.okButton = wxButton(self, wxID_OK, "OK")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: aboutDialog.__set_properties
        self.SetTitle("About DSCAS3")
        self.htmlWindow.SetSize((389, 245))
        self.okButton.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: aboutDialog.__do_layout
        sizer_3 = wxBoxSizer(wxVERTICAL)
        sizer_3.Add(self.htmlWindow, 1, wxALL|wxEXPAND, 5)
        sizer_3.Add(self.okButton, 0, wxALL|wxALIGN_CENTER_HORIZONTAL, 10)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        sizer_3.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class aboutDialog


