#!/usr/bin/env python
# generated by wxGlade 0.2.1cvs on Sun Jan 26 01:49:36 2003

from wxPython.wx import *

class graphEditorFrame(wxFrame):
    def __init__(self, *args, **kwds):
	# this class gets passed in as keyword argument (neat huh?)
	wxpcCanvas = kwds['wxpcCanvas']
	# I have to delete it from the keywords, because some of the wrapped
	# code doesn't like it
	del kwds['wxpcCanvas']
        # begin wxGlade: graphEditorFrame.__init__
        kwds["style"] = wxDEFAULT_FRAME_STYLE
        wxFrame.__init__(self, *args, **kwds)
        self.panel_2 = wxPanel(self, -1)
        self.window_2 = wxSplitterWindow(self.panel_2, -1)
        self.window_2_pane_2 = wxPanel(self.window_2, -1)
        self.window_2_pane_1 = wxPanel(self.window_2, -1)
        
        # Menu Bar
        self.frame_1_menubar = wxMenuBar()
        self.SetMenuBar(self.frame_1_menubar)
        self.fileNewId  =  wxNewId()
        self.fileOpenId  =  wxNewId()
        self.fileOpenSegmentId  =  wxNewId()
        self.fileSaveId  =  wxNewId()
        self.fileSaveSelectedId  =  wxNewId()
        self.fileExitId  =  wxNewId()
        self.helpContextHelpId  =  wxNewId()
        wxglade_tmp_menu = wxMenu()
        wxglade_tmp_menu.Append(self.fileNewId , "&New\tCtrl-N", "Create new network.", wxITEM_NORMAL)
        wxglade_tmp_menu.Append(self.fileOpenId , "&Open\tCtrl-O", "Open and load existing network.", wxITEM_NORMAL)
        wxglade_tmp_menu.Append(self.fileOpenSegmentId , "Open as Se&gment\tCtrl-G", "Open a DeVIDE network as a segment in the copy buffer.", wxITEM_NORMAL)
        wxglade_tmp_menu.Append(self.fileSaveId , "&Save\tCtrl-S", "Save the current network.", wxITEM_NORMAL)
        wxglade_tmp_menu.Append(self.fileSaveSelectedId , "Save se&lected Glyphs\tCtrl-L", "Save the selected glyphs as a network.", wxITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(self.fileExitId , "E&xit\tCtrl-Q", "Exit DeVIDE!", wxITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "&File")
        self.editMenu = wxMenu()
        self.frame_1_menubar.Append(self.editMenu, "&Edit")
        wxglade_tmp_menu = wxMenu()
        wxglade_tmp_menu.Append(self.helpContextHelpId , "&Context-sensitive Help\tF1", "", wxITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "&Help")
        # Menu Bar end
        self.frame_1_statusbar = self.CreateStatusBar(1)
        self.moduleCatsListCtrlId  =  wxNewId()
        self.moduleCatsListCtrl = wxListCtrl(self.window_2_pane_1, self.moduleCatsListCtrlId , style=wxLC_REPORT|wxSUNKEN_BORDER)
        self.modulesListCtrlId  =  wxNewId()
        self.modulesListCtrl = wxListCtrl(self.window_2_pane_1, self.modulesListCtrlId , style=wxLC_REPORT|wxLC_SINGLE_SEL|wxSUNKEN_BORDER)
        self.rescanButtonId  =  wxNewId()
        self.rescanButton = wxButton(self.window_2_pane_1, self.rescanButtonId , "Rescan")
        self.canvas = wxpcCanvas(self.window_2_pane_2, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: graphEditorFrame.__set_properties
        self.SetTitle("DeVIDE Graph Editor")
        self.frame_1_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_1_statusbar_fields = ["Welcome to the DeVIDE Graph Editor"]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        self.canvas.SetSize((599, 532))
        self.window_2.SetSize((784, 541))
        self.window_2.SplitVertically(self.window_2_pane_1, self.window_2_pane_2, 176)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: graphEditorFrame.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_5 = wxBoxSizer(wxVERTICAL)
        sizer_6 = wxBoxSizer(wxVERTICAL)
        sizer_8 = wxBoxSizer(wxVERTICAL)
        sizer_7 = wxBoxSizer(wxVERTICAL)
        sizer_7.Add(self.moduleCatsListCtrl, 2, wxBOTTOM|wxEXPAND, 7)
        sizer_7.Add(self.modulesListCtrl, 3, wxEXPAND, 0)
        sizer_7.Add(self.rescanButton, 0, wxTOP|wxBOTTOM|wxALIGN_CENTER_HORIZONTAL, 7)
        self.window_2_pane_1.SetAutoLayout(1)
        self.window_2_pane_1.SetSizer(sizer_7)
        sizer_7.Fit(self.window_2_pane_1)
        sizer_7.SetSizeHints(self.window_2_pane_1)
        sizer_8.Add(self.canvas, 1, wxEXPAND, 0)
        self.window_2_pane_2.SetAutoLayout(1)
        self.window_2_pane_2.SetSizer(sizer_8)
        sizer_8.Fit(self.window_2_pane_2)
        sizer_8.SetSizeHints(self.window_2_pane_2)
        sizer_6.Add(self.window_2, 1, wxEXPAND, 0)
        sizer_5.Add(sizer_6, 1, wxALL|wxEXPAND, 7)
        self.panel_2.SetAutoLayout(1)
        self.panel_2.SetSizer(sizer_5)
        sizer_5.Fit(self.panel_2)
        sizer_5.SetSizeHints(self.panel_2)
        sizer_1.Add(self.panel_2, 1, wxEXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class graphEditorFrame


