#!/usr/bin/env python
# generated by wxGlade 0.2.1cvs on Sun Jan 26 01:49:36 2003

from wxPython.wx import *

class graphEditorFrame(wxFrame):
    def __init__(self, *args, **kwds):
	# this class gets passed in as keyword argument (neat huh?)
	wxpcCanvas = kwds['wxpcCanvas']
	# I have to delete it from the keywords, because some of the wrapped
	# code doesn't like it
	del kwds['wxpcCanvas']
        # begin wxGlade: graphEditorFrame.__init__
        kwds["style"] = wxDEFAULT_FRAME_STYLE
        wxFrame.__init__(self, *args, **kwds)
        self.window_1 = wxSplitterWindow(self, -1)
        self.window_1_pane_2 = wxPanel(self.window_1, -1)
        self.window_1_pane_1 = wxPanel(self.window_1, -1)
        
        # Menu Bar
        self.frame_1_menubar = wxMenuBar()
        self.SetMenuBar(self.frame_1_menubar)
        self.fileNewId  =  wxNewId()
        self.fileOpenId  =  wxNewId()
        self.fileOpenSegmentId  =  wxNewId()
        self.fileSaveId  =  wxNewId()
        self.fileSaveSelectedId  =  wxNewId()
        self.fileExitId  =  wxNewId()
        self.helpContextHelpId  =  wxNewId()
        wxglade_tmp_menu = wxMenu()
        wxglade_tmp_menu.Append(self.fileNewId , "&New\tCtrl-N", "Create new network.", wxITEM_NORMAL)
        wxglade_tmp_menu.Append(self.fileOpenId , "&Open\tCtrl-O", "Open and load existing network.", wxITEM_NORMAL)
        wxglade_tmp_menu.Append(self.fileOpenSegmentId , "Open as Se&gment\tCtrl-G", "Open a DSCAS3 network as a segment in the copy buffer.", wxITEM_NORMAL)
        wxglade_tmp_menu.Append(self.fileSaveId , "&Save\tCtrl-S", "Save the current network.", wxITEM_NORMAL)
        wxglade_tmp_menu.Append(self.fileSaveSelectedId , "Save se&lected Glyphs\tCtrl-L", "Save the selected glyphs as a network.", wxITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(self.fileExitId , "E&xit\tCtrl-Q", "Exit DSCAS3!", wxITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "&File")
        self.editMenu = wxMenu()
        self.frame_1_menubar.Append(self.editMenu, "&Edit")
        wxglade_tmp_menu = wxMenu()
        wxglade_tmp_menu.Append(self.helpContextHelpId , "&Context-sensitive Help\tF1", "", wxITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "&Help")
        # Menu Bar end
        self.frame_1_statusbar = self.CreateStatusBar(1)
        self.treeCtrlId  =  wxNewId()
        self.treeCtrl = wxTreeCtrl(self.window_1_pane_1, self.treeCtrlId , style=wxTR_HAS_BUTTONS|wxTR_LINES_AT_ROOT|wxSUNKEN_BORDER)
        self.rescanButtonId  =  wxNewId()
        self.rescanButton = wxButton(self.window_1_pane_1, self.rescanButtonId , "Rescan")
        self.canvas = wxpcCanvas(self.window_1_pane_2)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: graphEditorFrame.__set_properties
        self.SetTitle("DSCAS3 Graph Editor")
        self.frame_1_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_1_statusbar_fields = ["Welcome to the DSCAS3 Graph Editor"]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        self.treeCtrl.SetSize((182, 400))
        self.window_1.SetSize((680, 431))
        self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2, 184)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: graphEditorFrame.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_2 = wxBoxSizer(wxVERTICAL)
        sizer_3 = wxBoxSizer(wxVERTICAL)
        sizer_3.Add(self.treeCtrl, 1, wxEXPAND, 0)
        sizer_3.Add(self.rescanButton, 0, wxALIGN_CENTER_HORIZONTAL, 0)
        self.window_1_pane_1.SetAutoLayout(1)
        self.window_1_pane_1.SetSizer(sizer_3)
        sizer_3.Fit(self.window_1_pane_1)
        sizer_3.SetSizeHints(self.window_1_pane_1)
        sizer_2.Add(self.canvas, 1, wxEXPAND, 0)
        self.window_1_pane_2.SetAutoLayout(1)
        self.window_1_pane_2.SetSizer(sizer_2)
        sizer_2.Fit(self.window_1_pane_2)
        sizer_2.SetSizeHints(self.window_1_pane_2)
        sizer_1.Add(self.window_1, 1, wxALL|wxEXPAND, 7)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class graphEditorFrame


