#!/usr/bin/env python
# generated by wxGlade 0.2.1cvs on Thu Jan 23 15:01:14 2003

from wxPython.wx import *

class mainFrame(wxFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: mainFrame.__init__
        kwds["style"] = wxDEFAULT_FRAME_STYLE
        wxFrame.__init__(self, *args, **kwds)
        self.progressText = wxStaticText(self, -1, "This is quite a long progress message so that eek.")
        self.progressGauge = wxGauge(self, -1, 100)
        
        # Menu Bar
        self.frame_1_menubar = wxMenuBar()
        self.SetMenuBar(self.frame_1_menubar)
        wxglade_tmp_menu = wxMenu()
        self.fileExitId  =  wxNewId()
        wxglade_tmp_menu.Append(self.fileExitId , "E&xit", "Exit DSCAS")
        self.frame_1_menubar.Append(wxglade_tmp_menu, "&File")
        wxglade_tmp_menu = wxMenu()
        self.windowGraphEditorId  =  wxNewId()
        wxglade_tmp_menu.Append(self.windowGraphEditorId , "&Graph Editor", "Open up the graph editor window")
        self.windowPythonShellId  =  wxNewId()
        wxglade_tmp_menu.Append(self.windowPythonShellId , "&Python Shell", "Show the Python Shell interface")
        self.frame_1_menubar.Append(wxglade_tmp_menu, "&Window")
        wxglade_tmp_menu = wxMenu()
        self.helpAboutId  =  wxNewId()
        wxglade_tmp_menu.Append(self.helpAboutId , "&About", "Get information about DSCAS3")
        self.frame_1_menubar.Append(wxglade_tmp_menu, "&Help")
        # Menu Bar end
        self.frame_1_statusbar = self.CreateStatusBar(1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: mainFrame.__set_properties
        self.SetTitle("DSCAS3 main window")
        self.progressText.SetFont(wxFont(14, wxDEFAULT, wxNORMAL, wxNORMAL, 0, ""))
        self.progressGauge.SetBackgroundColour(wxColour(50, 153, 204))
        self.progressGauge.SetForegroundColour(wxColour(0, 0, 0))
        self.frame_1_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_1_statusbar_fields = ["Welcome to DSCAS3"]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: mainFrame.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_2 = wxBoxSizer(wxHORIZONTAL)
        sizer_1.Add(self.progressText, 0, wxLEFT|wxRIGHT|wxTOP, 5)
        sizer_2.Add(self.progressGauge, 1, wxLEFT|wxRIGHT|wxBOTTOM, 5)
        sizer_1.Add(sizer_2, 0, wxEXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class mainFrame


