#!/usr/bin/env python
# generated by wxGlade 0.3.2pre2 on Fri Feb 27 12:51:36 2004

import wx
import module_kits.wx_kit

class pythonShellFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: pythonShellFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.statusBar = self.CreateStatusBar(1, 0)
        self.pyShell = module_kits.wx_kit.dvshell.DVShell(self.panel_1, -1)
        self.loadSnippetButton = wx.Button(self.panel_1, -1, "Run Snippet")
        self.closeButton = wx.Button(self.panel_1, -1, "Close")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: pythonShellFrame.__set_properties
        self.SetTitle("DeVIDE Python Introspection")
        self.SetSize((640, 480))
        self.statusBar.SetStatusWidths([-1])
        # statusbar fields
        statusBar_fields = ["Welcome to the Python Shell!"]
        for i in range(len(statusBar_fields)):
            self.statusBar.SetStatusText(statusBar_fields[i], i)
        self.pyShell.SetFocus()
        self.panel_1.SetSize((632, 428))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: pythonShellFrame.__do_layout
        topSizer = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.pyShell, 1, wx.EXPAND, 0)
        sizer_6.Add(self.loadSnippetButton, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 4)
        sizer_6.Add(self.closeButton, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(sizer_6, 0, wx.TOP|wx.ALIGN_RIGHT, 7)
        sizer_2.Add(sizer_3, 1, wx.ALL|wx.EXPAND, 7)
        self.panel_1.SetAutoLayout(1)
        self.panel_1.SetSizer(sizer_2)
        topSizer.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(topSizer)
        self.Layout()
        # end wxGlade

# end of class pythonShellFrame


class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

# end of class MyFrame1


