# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkBYUReader(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkBYUReader(), 'Reading vtkBYU.',
            (), ('vtkBYU',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
