# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkChacoReader(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkChacoReader(), 'Reading vtkChaco.',
            (), ('vtkChaco',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
