# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkDICOMImageReader(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkDICOMImageReader(), 'Reading vtkDICOMImage.',
            (), ('vtkDICOMImage',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
