# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkDelimitedTextReader(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkDelimitedTextReader(), 'Reading vtkDelimitedText.',
            (), ('vtkDelimitedText',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
