# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkExtractSelectedIds(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkExtractSelectedIds(), 'Processing.',
            ('vtkDataSet', 'vtkSelection'), ('vtkDataSet',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
