# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkExtractSelectedFrustum(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkExtractSelectedFrustum(), 'Processing.',
            ('vtkDataSet', 'vtkSelection'), ('vtkDataSet',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
