# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkEnSightGoldBinaryReader(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkEnSightGoldBinaryReader(), 'Reading vtkEnSightGoldBinary.',
            (), ('vtkEnSightGoldBinary',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
