# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkFacetReader(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkFacetReader(), 'Reading vtkFacet.',
            (), ('vtkFacet',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
