# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkGenericDataObjectWriter(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkGenericDataObjectWriter(), 'Writing vtkGenericDataObject.',
            ('vtkGenericDataObject',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
