# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkGenericEnSightReader(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkGenericEnSightReader(), 'Reading vtkGenericEnSight.',
            (), ('vtkGenericEnSight',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
