# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkHyperOctreeFractalSource(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkHyperOctreeFractalSource(), 'Processing.',
            (), ('vtkHyperOctree',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
