# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkHyperOctreeSampleFunction(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkHyperOctreeSampleFunction(), 'Processing.',
            (), ('vtkHyperOctree',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
