# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkImageToStructuredPoints(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkImageToStructuredPoints(), 'Processing.',
            ('vtkImageData', 'vtkImageData'), ('vtkStructuredPoints',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
