# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkImplicitFunctionToImageStencil(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkImplicitFunctionToImageStencil(), 'Processing.',
            (), ('vtkImageStencilData',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
