# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkMINCImageReader(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkMINCImageReader(), 'Reading vtkMINCImage.',
            (), ('vtkMINCImage',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
