# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkMultiGroupDataExtractGroup(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkMultiGroupDataExtractGroup(), 'Processing.',
            ('vtkMultiGroupDataSet',), ('vtkMultiGroupDataSet',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
