# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkMFIXReader(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkMFIXReader(), 'Reading vtkMFIX.',
            (), ('vtkMFIX',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
