# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkMetaImageReader(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkMetaImageReader(), 'Reading vtkMetaImage.',
            (), ('vtkMetaImage',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
