# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkMCubesWriter(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkMCubesWriter(), 'Writing vtkMCubes.',
            ('vtkMCubes',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
