# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkMassProperties(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkMassProperties(), 'Processing.',
            ('vtkPolyData',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
