# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkMetaImageWriter(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkMetaImageWriter(), 'Writing vtkMetaImage.',
            ('vtkMetaImage',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
