# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkPolyDataWriter(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkPolyDataWriter(), 'Writing vtkPolyData.',
            ('vtkPolyData',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
