# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkPDBReader(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkPDBReader(), 'Reading vtkPDB.',
            (), ('vtkPDB',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
