# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkRandomGraphSource(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkRandomGraphSource(), 'Processing.',
            (), ('vtkGraph',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
