# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkRTXMLPolyDataReader(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkRTXMLPolyDataReader(), 'Reading vtkRTXMLPolyData.',
            (), ('vtkRTXMLPolyData',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
