# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkSTLReader(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkSTLReader(), 'Reading vtkSTL.',
            (), ('vtkSTL',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
