# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkSurfaceReconstructionFilter(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkSurfaceReconstructionFilter(), 'Processing.',
            ('vtkDataSet',), ('vtkImageData',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
