# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkStructuredPointsReader(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkStructuredPointsReader(), 'Reading vtkStructuredPoints.',
            (), ('vtkStructuredPoints',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
