# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkSimplePointsReader(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkSimplePointsReader(), 'Reading vtkSimplePoints.',
            (), ('vtkSimplePoints',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
