# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkThreshold(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkThreshold(), 'Processing.',
            ('vtkDataSet',), ('vtkUnstructuredGrid',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
