# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkTableWriter(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkTableWriter(), 'Writing vtkTable.',
            ('vtkTable',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
