# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkTIFFWriter(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkTIFFWriter(), 'Writing vtkTIFF.',
            ('vtkTIFF',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
