# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkTreeMapLayout(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkTreeMapLayout(), 'Processing.',
            ('vtkTree',), ('vtkTree',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
