# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkUGFacetReader(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkUGFacetReader(), 'Reading vtkUGFacet.',
            (), ('vtkUGFacet',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
