# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkXYZMolReader(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXYZMolReader(), 'Reading vtkXYZMol.',
            (), ('vtkXYZMol',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
