# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkXMLPRectilinearGridReader(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXMLPRectilinearGridReader(), 'Reading vtkXMLPRectilinearGrid.',
            (), ('vtkXMLPRectilinearGrid',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
