# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkXMLHierarchicalBoxDataReader(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXMLHierarchicalBoxDataReader(), 'Reading vtkXMLHierarchicalBoxData.',
            (), ('vtkXMLHierarchicalBoxData',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
