# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkXMLHyperOctreeWriter(SimpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        SimpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXMLHyperOctreeWriter(), 'Writing vtkXMLHyperOctree.',
            ('vtkXMLHyperOctree',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
