# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkXMLStructuredGridWriter(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkXMLStructuredGridWriter(), 'Writing vtkXMLStructuredGrid.',
            ('vtkXMLStructuredGrid',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
