# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from module_kits.vtk_kit.mixins import SimpleVTKClassModuleBase
import vtk

class vtkXMLImageDataReader(SimpleVTKClassModuleBase):
    def __init__(self, module_manager):
        SimpleVTKClassModuleBase.__init__(
            self, module_manager,
            vtk.vtkXMLImageDataReader(), 'Reading vtkXMLImageData.',
            (), ('vtkXMLImageData',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
