#!/usr/bin/env python
# generated by wxGlade 0.2.1 on Fri Feb  7 18:13:59 2003

from wxPython.wx import *

class dicomRDRViewFrame(wxFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: dicomRDRViewFrame.__init__
        kwds["style"] = wxCAPTION|wxMINIMIZE_BOX|wxMAXIMIZE_BOX|wxSYSTEM_MENU|wxRESIZE_BORDER
        wxFrame.__init__(self, *args, **kwds)
        self.label_1 = wxStaticText(self, -1, "DICOM Directory")
        self.DIRNAME_TEXT_ID  =  wxNewId()
        self.dirname_text = wxTextCtrl(self, self.DIRNAME_TEXT_ID , "")
        self.BROWSE_BUTTON_ID  =  wxNewId()
        self.browse_button = wxButton(self, self.BROWSE_BUTTON_ID , "Browse...")
        self.label_4 = wxStaticText(self, -1, "Series Instance Index")
        self.SI_IDX_ID  =  wxNewId()
        self.si_idx_spin = wxSpinCtrl(self, self.SI_IDX_ID , "0", min=0, max=100, style=wxSP_ARROW_KEYS)
        self.label_5 = wxStaticText(self, -1, "UID")
        self.si_uid_text = wxTextCtrl(self, -1, "", style=wxTE_READONLY|wxHSCROLL)
        self.label_9 = wxStaticText(self, -1, "Study Description:")
        self.study_description_text = wxTextCtrl(self, -1, "", style=wxTE_READONLY|wxHSCROLL)
        self.label_10 = wxStaticText(self, -1, "Referring Physician:")
        self.referring_physician_text = wxTextCtrl(self, -1, "", style=wxTE_READONLY|wxHSCROLL)
        self.label_11 = wxStaticText(self, -1, "Dimensions:")
        self.dimensions_text = wxTextCtrl(self, -1, "", style=wxTE_READONLY|wxHSCROLL)
        self.label_2 = wxStaticText(self, -1, "Examine the")
        self.VTK_OBJECT_CHOICE_ID  =  wxNewId()
        self.object_choice = wxChoice(self, self.VTK_OBJECT_CHOICE_ID , choices=["vtkDICOMVolumeReader"])
        self.label_3 = wxStaticText(self, -1, "or")
        self.VTK_PIPELINE_ID  =  wxNewId()
        self.pipeline_button = wxButton(self, self.VTK_PIPELINE_ID , "Pipeline")
        self.cancel_button = wxButton(self, wxID_CANCEL, "Cancel")
        self.SYNC_ID  =  wxNewId()
        self.sync_button = wxButton(self, self.SYNC_ID , "Sync")
        self.APPLY_ID  =  wxNewId()
        self.apply_button = wxButton(self, self.APPLY_ID , "Apply")
        self.EXECUTE_ID  =  wxNewId()
        self.execute_button = wxButton(self, self.EXECUTE_ID , "Execute")
        self.ok_button = wxButton(self, wxID_OK, "OK")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: dicomRDRViewFrame.__set_properties
        self.SetTitle("vtk_dicom_rdr configuration")
        self.si_uid_text.SetBackgroundColour(wxColour(192, 192, 192))
        self.study_description_text.SetBackgroundColour(wxColour(192, 192, 192))
        self.referring_physician_text.SetBackgroundColour(wxColour(192, 192, 192))
        self.dimensions_text.SetBackgroundColour(wxColour(192, 192, 192))
        self.object_choice.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: dicomRDRViewFrame.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_2 = wxBoxSizer(wxHORIZONTAL)
        sizer_4 = wxBoxSizer(wxHORIZONTAL)
        mdata_sizer = wxFlexGridSizer(3, 2, 0, 0)
        sizer_5 = wxBoxSizer(wxHORIZONTAL)
        sizer_3 = wxBoxSizer(wxHORIZONTAL)
        sizer_3.Add(self.label_1, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 2)
        sizer_3.Add(self.dirname_text, 1, wxALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(self.browse_button, 0, wxALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(sizer_3, 1, wxALL|wxEXPAND, 5)
        sizer_5.Add(self.label_4, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 2)
        sizer_5.Add(self.si_idx_spin, 0, wxALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(self.label_5, 0, wxLEFT|wxRIGHT|wxALIGN_CENTER_VERTICAL, 2)
        sizer_5.Add(self.si_uid_text, 1, wxALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(sizer_5, 1, wxALL|wxEXPAND, 5)
        mdata_sizer.Add(self.label_9, 0, wxLEFT|wxRIGHT|wxALIGN_CENTER_VERTICAL, 2)
        mdata_sizer.Add(self.study_description_text, 1, wxLEFT|wxEXPAND, 2)
        mdata_sizer.Add(self.label_10, 0, wxLEFT|wxRIGHT|wxALIGN_CENTER_VERTICAL, 2)
        mdata_sizer.Add(self.referring_physician_text, 1, wxLEFT|wxEXPAND, 2)
        mdata_sizer.Add(self.label_11, 0, wxLEFT|wxRIGHT|wxALIGN_CENTER_VERTICAL, 2)
        mdata_sizer.Add(self.dimensions_text, 1, wxLEFT|wxEXPAND, 2)
        mdata_sizer.AddGrowableCol(1)
        sizer_1.Add(mdata_sizer, 0, wxALL|wxEXPAND, 5)
        sizer_4.Add(self.label_2, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 2)
        sizer_4.Add(self.object_choice, 0, wxALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(self.label_3, 0, wxLEFT|wxRIGHT|wxALIGN_CENTER_VERTICAL, 2)
        sizer_4.Add(self.pipeline_button, 0, wxALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(sizer_4, 1, wxALL, 5)
        sizer_2.Add(self.cancel_button, 0, wxALL, 4)
        sizer_2.Add(self.sync_button, 0, wxALL, 4)
        sizer_2.Add(self.apply_button, 0, wxALL, 4)
        sizer_2.Add(self.execute_button, 0, wxALL, 4)
        sizer_2.Add(self.ok_button, 0, wxALL, 4)
        sizer_1.Add(sizer_2, 1, wxALL, 5)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class dicomRDRViewFrame


