#!/usr/bin/env python
# generated by wxGlade 0.2.1cvs on Fri Jan 17 17:25:19 2003

from wxPython.wx import *
from wxPython.grid import *
from vtk.wx.wxVTKRenderWindowInteractor import wxVTKRenderWindowInteractor

class slice3d_vwr_frame(wxFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: slice3d_vwr_frame.__init__
        kwds["style"] = wxDEFAULT_FRAME_STYLE
        wxFrame.__init__(self, *args, **kwds)
        self.panel_1 = wxPanel(self, -1)
        self.notebook_1_copy = wxNotebook(self.panel_1, -1, style=0)
        self.notebook_1_pane_3_copy = wxPanel(self.notebook_1_copy, -1)
        self.voiPanel = wxPanel(self.notebook_1_copy, -1)
        self.notebook_1_pane_1_copy = wxPanel(self.notebook_1_copy, -1)
        self.threedRWI = wxVTKRenderWindowInteractor(self.panel_1, -1)
        self.spointsGrid = wxGrid(self.notebook_1_pane_1_copy, -1)
        self.pointsSelectAllButtonId  =  wxNewId()
        self.pointsSelectAllButton = wxButton(self.notebook_1_pane_1_copy, self.pointsSelectAllButtonId , "Select all")
        self.pointsDeselectAllButtonId  =  wxNewId()
        self.pointsDeselectAllButton = wxButton(self.notebook_1_pane_1_copy, self.pointsDeselectAllButtonId , "Deselect all")
        self.pointsRemoveButtonId  =  wxNewId()
        self.pointsRemoveButton = wxButton(self.notebook_1_pane_1_copy, self.pointsRemoveButtonId , "Remove")
        self.voiPanel.widgetEnabledCboxId  =  wxNewId()
        self.voiPanel.widgetEnabledCbox = wxCheckBox(self.voiPanel, self.voiPanel.widgetEnabledCboxId , "Widget enabled")
        self.label_7_copy_copy = wxStaticText(self.voiPanel, -1, "Absolute bounds")
        self.voiPanel.boundsText = wxTextCtrl(self.voiPanel, -1, "", style=wxTE_READONLY)
        self.label_7_copy_1 = wxStaticText(self.voiPanel, -1, "Discrete extent")
        self.voiPanel.extentText = wxTextCtrl(self.voiPanel, -1, "")
        self.pipelineButtonId  =  wxNewId()
        self.pipelineButton = wxButton(self.notebook_1_pane_3_copy, self.pipelineButtonId , "Pipeline")
        self.resetButtonId  =  wxNewId()
        self.resetButton = wxButton(self.notebook_1_pane_3_copy, self.resetButtonId , "Reset")
        self.surfacePickActionRB = wxRadioBox(self.notebook_1_pane_3_copy, -1, "Surface pick action", choices=["None", "Place point", "Configure picked object"], majorDimension=1, style=wxRA_SPECIFY_COLS)
        self.sliceNameChoice = wxChoice(self.panel_1, -1, choices=["choice 1"])
        self.destroySliceButtonId  =  wxNewId()
        self.button_3 = wxButton(self.panel_1, self.destroySliceButtonId , "Destroy Slice")
        self.createSliceText = wxTextCtrl(self.panel_1, -1, "")
        self.createSliceButtonId  =  wxNewId()
        self.button_2 = wxButton(self.panel_1, self.createSliceButtonId , "Create Slice")
        self.static_line_1 = wxStaticLine(self.panel_1, -1)
        self.sliceEnabledCheckBoxId  =  wxNewId()
        self.sliceEnabledCheckBox = wxCheckBox(self.panel_1, self.sliceEnabledCheckBoxId , "Enabled")
        self.sliceInteractionCheckBoxId  =  wxNewId()
        self.sliceInteractionCheckBox = wxCheckBox(self.panel_1, self.sliceInteractionCheckBoxId , "Interaction")
        self.acsChoiceId  =  wxNewId()
        self.choice_1 = wxChoice(self.panel_1, self.acsChoiceId , choices=["Set Axial", "Set Coronal", "Set Sagittal"])
        self.pushSliceLabel = wxStaticText(self.panel_1, -1, "Push slice")
        self.pushSliceSpinCtrlId  =  wxNewId()
        self.pushSliceSpinCtrl = wxSpinCtrl(self.panel_1, self.pushSliceSpinCtrlId , "0", min=-100, max=100, style=wxSP_ARROW_KEYS)
        self.label_1_copy_copy = wxStaticText(self.panel_1, -1, "Cursor at")
        self.sliceCursorText = wxTextCtrl(self.panel_1, -1, "")
        self.label_4_copy_copy = wxStaticText(self.panel_1, -1, "Name")
        self.sliceCursorNameCombo = wxComboBox(self.panel_1, -1, choices=["Point 1"], style=wxCB_DROPDOWN)
        self.sliceStoreButtonId  =  wxNewId()
        self.button_6_copy_copy = wxButton(self.panel_1, self.sliceStoreButtonId , "Store")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: slice3d_vwr_frame.__set_properties
        self.SetTitle("DSCAS3 Slice/3D Viewer")
        self.SetSize((763, 648))
        self.spointsGrid.CreateGrid(0, 3)
        self.spointsGrid.SetColLabelValue(0, "World")
        self.spointsGrid.SetColLabelValue(1, "Discrete")
        self.spointsGrid.SetColLabelValue(2, "Value")
        self.spointsGrid.SetSize((375, 228))
        self.surfacePickActionRB.SetSelection(0)
        self.sliceNameChoice.SetSelection(0)
        self.sliceEnabledCheckBox.SetValue(1)
        self.sliceInteractionCheckBox.SetValue(1)
        self.choice_1.SetSelection(0)
        self.sliceCursorNameCombo.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: slice3d_vwr_frame.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_8 = wxBoxSizer(wxVERTICAL)
        sizer_9 = wxBoxSizer(wxHORIZONTAL)
        sizer_21 = wxBoxSizer(wxVERTICAL)
        sizer_13_copy_copy = wxBoxSizer(wxHORIZONTAL)
        grid_sizer_1_copy_copy = wxFlexGridSizer(2, 2, 0, 0)
        sizer_3 = wxBoxSizer(wxHORIZONTAL)
        sizer_20_copy_1_copy = wxBoxSizer(wxHORIZONTAL)
        grid_sizer_5 = wxFlexGridSizer(2, 2, 0, 2)
        sizer_18_copy = wxBoxSizer(wxHORIZONTAL)
        sizer_19_copy = wxBoxSizer(wxVERTICAL)
        sizer_3_copy = wxBoxSizer(wxVERTICAL)
        grid_sizer_4_copy = wxFlexGridSizer(2, 2, 0, 0)
        sizer_10_copy = wxBoxSizer(wxVERTICAL)
        sizer_11_copy = wxBoxSizer(wxHORIZONTAL)
        sizer_2 = wxBoxSizer(wxVERTICAL)
        sizer_2.Add(self.threedRWI, 1, wxEXPAND, 0)
        sizer_8.Add(sizer_2, 1, wxEXPAND, 0)
        sizer_10_copy.Add(self.spointsGrid, 1, wxEXPAND, 0)
        sizer_11_copy.Add(self.pointsSelectAllButton, 0, 0, 0)
        sizer_11_copy.Add(self.pointsDeselectAllButton, 0, 0, 0)
        sizer_11_copy.Add(self.pointsRemoveButton, 0, 0, 0)
        sizer_10_copy.Add(sizer_11_copy, 0, wxEXPAND, 0)
        self.notebook_1_pane_1_copy.SetAutoLayout(1)
        self.notebook_1_pane_1_copy.SetSizer(sizer_10_copy)
        sizer_10_copy.Fit(self.notebook_1_pane_1_copy)
        sizer_10_copy.SetSizeHints(self.notebook_1_pane_1_copy)
        sizer_3_copy.Add(self.voiPanel.widgetEnabledCbox, 0, 0, 0)
        grid_sizer_4_copy.Add(self.label_7_copy_copy, 0, wxLEFT|wxRIGHT|wxALIGN_CENTER_VERTICAL, 2)
        grid_sizer_4_copy.Add(self.voiPanel.boundsText, 1, wxLEFT|wxRIGHT|wxEXPAND, 2)
        grid_sizer_4_copy.Add(self.label_7_copy_1, 0, wxLEFT|wxRIGHT|wxALIGN_CENTER_VERTICAL, 2)
        grid_sizer_4_copy.Add(self.voiPanel.extentText, 0, wxLEFT|wxRIGHT|wxEXPAND, 2)
        grid_sizer_4_copy.AddGrowableCol(1)
        sizer_3_copy.Add(grid_sizer_4_copy, 1, wxEXPAND, 0)
        self.voiPanel.SetAutoLayout(1)
        self.voiPanel.SetSizer(sizer_3_copy)
        sizer_3_copy.Fit(self.voiPanel)
        sizer_3_copy.SetSizeHints(self.voiPanel)
        sizer_19_copy.Add(self.pipelineButton, 0, wxALL, 2)
        sizer_19_copy.Add(self.resetButton, 0, wxALL, 2)
        sizer_18_copy.Add(sizer_19_copy, 0, wxEXPAND, 0)
        sizer_18_copy.Add(self.surfacePickActionRB, 1, wxALL, 2)
        self.notebook_1_pane_3_copy.SetAutoLayout(1)
        self.notebook_1_pane_3_copy.SetSizer(sizer_18_copy)
        sizer_18_copy.Fit(self.notebook_1_pane_3_copy)
        sizer_18_copy.SetSizeHints(self.notebook_1_pane_3_copy)
        self.notebook_1_copy.AddPage(self.notebook_1_pane_1_copy, "Selected points")
        self.notebook_1_copy.AddPage(self.voiPanel, "Volume of Interest")
        self.notebook_1_copy.AddPage(self.notebook_1_pane_3_copy, "Global Operations")
        sizer_9.Add(wxNotebookSizer(self.notebook_1_copy), 1, 0, 0)
        grid_sizer_5.Add(self.sliceNameChoice, 0, wxEXPAND, 0)
        grid_sizer_5.Add(self.button_3, 0, 0, 0)
        grid_sizer_5.Add(self.createSliceText, 0, wxEXPAND, 0)
        grid_sizer_5.Add(self.button_2, 0, 0, 0)
        grid_sizer_5.AddGrowableCol(0)
        sizer_21.Add(grid_sizer_5, 1, wxALL|wxEXPAND, 2)
        sizer_21.Add(self.static_line_1, 0, wxTOP|wxBOTTOM|wxEXPAND, 6)
        sizer_20_copy_1_copy.Add(self.sliceEnabledCheckBox, 0, wxALIGN_CENTER_VERTICAL, 0)
        sizer_20_copy_1_copy.Add(self.sliceInteractionCheckBox, 0, wxALIGN_CENTER_VERTICAL, 0)
        sizer_21.Add(sizer_20_copy_1_copy, 0, wxEXPAND, 0)
        sizer_3.Add(self.choice_1, 0, wxALL, 2)
        sizer_3.Add(self.pushSliceLabel, 0, wxALL|wxALIGN_CENTER_VERTICAL, 2)
        sizer_3.Add(self.pushSliceSpinCtrl, 0, wxALL, 2)
        sizer_21.Add(sizer_3, 0, wxEXPAND, 0)
        grid_sizer_1_copy_copy.Add(self.label_1_copy_copy, 0, wxLEFT|wxRIGHT|wxALIGN_CENTER_VERTICAL, 2)
        grid_sizer_1_copy_copy.Add(self.sliceCursorText, 0, wxEXPAND, 0)
        grid_sizer_1_copy_copy.Add(self.label_4_copy_copy, 0, wxLEFT|wxRIGHT|wxALIGN_CENTER_VERTICAL, 2)
        grid_sizer_1_copy_copy.Add(self.sliceCursorNameCombo, 0, wxEXPAND, 0)
        grid_sizer_1_copy_copy.AddGrowableCol(1)
        sizer_13_copy_copy.Add(grid_sizer_1_copy_copy, 1, wxEXPAND, 0)
        sizer_13_copy_copy.Add(self.button_6_copy_copy, 0, wxEXPAND, 0)
        sizer_21.Add(sizer_13_copy_copy, 0, wxEXPAND, 0)
        sizer_9.Add(sizer_21, 1, 0, 0)
        sizer_8.Add(sizer_9, 0, wxEXPAND, 0)
        self.panel_1.SetAutoLayout(1)
        self.panel_1.SetSizer(sizer_8)
        sizer_8.Fit(self.panel_1)
        sizer_8.SetSizeHints(self.panel_1)
        sizer_1.Add(self.panel_1, 1, wxEXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class slice3d_vwr_frame


class slice_viewer_frame(wxFrame):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

# end of class slice_viewer_frame


