#!/usr/bin/env python
# generated by wxGlade 0.2.1cvs on Fri Jan 17 17:25:19 2003

from wxPython.wx import *
from wxPython.grid import *
from vtk.wx.wxVTKRenderWindowInteractor import wxVTKRenderWindowInteractor

class slice3d_vwr_frame(wxFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: slice3d_vwr_frame.__init__
        kwds["style"] = wxDEFAULT_FRAME_STYLE
        wxFrame.__init__(self, *args, **kwds)
        self.notebook_2 = wxNotebook(self, -1, style=0)
        self.notebook_2_pane_1 = wxPanel(self.notebook_2, -1)
        self.notebook_1 = wxNotebook(self, -1, style=0)
        self.notebook_1_pane_1 = wxPanel(self.notebook_1, -1)
        self.window_1 = wxSplitterWindow(self, -1)
        self.window_1_pane_2 = wxPanel(self.window_1, -1)
        self.window_3 = wxSplitterWindow(self.window_1_pane_2, -1)
        self.window_3_pane_2 = wxPanel(self.window_3, -1)
        self.window_3_pane_1 = wxPanel(self.window_3, -1)
        self.window_1_pane_1 = wxPanel(self.window_1, -1)
        self.threedRWI = wxVTKRenderWindowInteractor(self.window_1_pane_1, -1)
        self.ortho1RWI = wxVTKRenderWindowInteractor(self.window_3_pane_1, -1)
        self.ortho2RWI = wxVTKRenderWindowInteractor(self.window_3_pane_2, -1)
        self.pipelineButton = wxButton(self, -1, "Pipeline")
        self.confPickedButton = wxButton(self, -1, "Conf Picked")
        self.resetButton = wxButton(self, -1, "Reset")
        self.grid_1 = wxGrid(self.notebook_1_pane_1, -1)
        self.button_3 = wxButton(self.notebook_1_pane_1, -1, "Select all")
        self.button_4 = wxButton(self.notebook_1_pane_1, -1, "Deselect all")
        self.button_5 = wxButton(self.notebook_1_pane_1, -1, "Remove")
        self.checkbox_1 = wxCheckBox(self.notebook_2_pane_1, -1, "Enabled")
        self.label_1 = wxStaticText(self.notebook_2_pane_1, -1, "Cursor at")
        self.text_ctrl_1 = wxTextCtrl(self.notebook_2_pane_1, -1, "")
        self.Name = wxStaticText(self.notebook_2_pane_1, -1, "label_2")
        self.combo_box_1 = wxComboBox(self.notebook_2_pane_1, -1, choices=["choice 1"], style=wxCB_DROPDOWN)
        self.button_6 = wxButton(self.notebook_2_pane_1, -1, "Store")
        self.notebook_2_pane_2 = wxPanel(self.notebook_2, -1)
        self.notebook_2_pane_3 = wxPanel(self.notebook_2, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: slice3d_vwr_frame.__set_properties
        self.SetTitle("DSCAS3 Slice/3D Viewer")
        self.SetSize((741, 620))
        self.window_3.SplitHorizontally(self.window_3_pane_1, self.window_3_pane_2, 268)
        self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2, 530)
        self.grid_1.CreateGrid(10, 2)
        self.grid_1.EnableEditing(0)
        self.grid_1.EnableDragGridSize(0)
        self.grid_1.SetSelectionMode(wxGrid.wxGridSelectRows)
        self.grid_1.SetColLabelValue(0, "Position")
        self.grid_1.SetColLabelValue(1, "Value")
        self.grid_1.SetSize((364, 100))
        self.combo_box_1.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: slice3d_vwr_frame.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_9 = wxBoxSizer(wxHORIZONTAL)
        sizer_12 = wxBoxSizer(wxVERTICAL)
        sizer_13 = wxBoxSizer(wxHORIZONTAL)
        grid_sizer_1 = wxFlexGridSizer(2, 2, 0, 0)
        sizer_10 = wxBoxSizer(wxVERTICAL)
        sizer_11 = wxBoxSizer(wxHORIZONTAL)
        sizer_8 = wxBoxSizer(wxHORIZONTAL)
        sizer_2 = wxBoxSizer(wxVERTICAL)
        sizer_5 = wxBoxSizer(wxHORIZONTAL)
        sizer_7 = wxBoxSizer(wxHORIZONTAL)
        sizer_6 = wxBoxSizer(wxHORIZONTAL)
        sizer_4 = wxBoxSizer(wxHORIZONTAL)
        sizer_4.Add(self.threedRWI, 1, wxEXPAND, 0)
        self.window_1_pane_1.SetAutoLayout(1)
        self.window_1_pane_1.SetSizer(sizer_4)
        sizer_4.Fit(self.window_1_pane_1)
        sizer_4.SetSizeHints(self.window_1_pane_1)
        sizer_6.Add(self.ortho1RWI, 1, wxEXPAND, 0)
        self.window_3_pane_1.SetAutoLayout(1)
        self.window_3_pane_1.SetSizer(sizer_6)
        sizer_6.Fit(self.window_3_pane_1)
        sizer_6.SetSizeHints(self.window_3_pane_1)
        sizer_7.Add(self.ortho2RWI, 1, wxEXPAND, 0)
        self.window_3_pane_2.SetAutoLayout(1)
        self.window_3_pane_2.SetSizer(sizer_7)
        sizer_7.Fit(self.window_3_pane_2)
        sizer_7.SetSizeHints(self.window_3_pane_2)
        sizer_5.Add(self.window_3, 1, wxEXPAND, 0)
        self.window_1_pane_2.SetAutoLayout(1)
        self.window_1_pane_2.SetSizer(sizer_5)
        sizer_5.Fit(self.window_1_pane_2)
        sizer_5.SetSizeHints(self.window_1_pane_2)
        sizer_2.Add(self.window_1, 1, wxEXPAND, 0)
        sizer_1.Add(sizer_2, 1, wxEXPAND, 0)
        sizer_8.Add(self.pipelineButton, 0, 0, 0)
        sizer_8.Add(self.confPickedButton, 0, 0, 0)
        sizer_8.Add(self.resetButton, 0, 0, 0)
        sizer_1.Add(sizer_8, 0, 0, 0)
        sizer_10.Add(self.grid_1, 0, wxEXPAND, 0)
        sizer_11.Add(self.button_3, 0, 0, 0)
        sizer_11.Add(self.button_4, 0, 0, 0)
        sizer_11.Add(self.button_5, 0, 0, 0)
        sizer_10.Add(sizer_11, 0, wxEXPAND, 0)
        self.notebook_1_pane_1.SetAutoLayout(1)
        self.notebook_1_pane_1.SetSizer(sizer_10)
        sizer_10.Fit(self.notebook_1_pane_1)
        sizer_10.SetSizeHints(self.notebook_1_pane_1)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Selected points")
        sizer_9.Add(wxNotebookSizer(self.notebook_1), 1, 0, 0)
        sizer_12.Add(self.checkbox_1, 0, 0, 0)
        grid_sizer_1.Add(self.label_1, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_1, 0, wxEXPAND, 0)
        grid_sizer_1.Add(self.Name, 0, 0, 0)
        grid_sizer_1.Add(self.combo_box_1, 0, wxEXPAND, 0)
        grid_sizer_1.AddGrowableCol(1)
        sizer_13.Add(grid_sizer_1, 1, wxEXPAND, 0)
        sizer_13.Add(self.button_6, 0, wxEXPAND, 0)
        sizer_12.Add(sizer_13, 0, wxEXPAND, 0)
        self.notebook_2_pane_1.SetAutoLayout(1)
        self.notebook_2_pane_1.SetSizer(sizer_12)
        sizer_12.Fit(self.notebook_2_pane_1)
        sizer_12.SetSizeHints(self.notebook_2_pane_1)
        self.notebook_2.AddPage(self.notebook_2_pane_1, "Axial")
        self.notebook_2.AddPage(self.notebook_2_pane_2, "Coronal")
        self.notebook_2.AddPage(self.notebook_2_pane_3, "Sagittal")
        sizer_9.Add(wxNotebookSizer(self.notebook_2), 1, wxEXPAND, 0)
        sizer_1.Add(sizer_9, 0, wxEXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class slice3d_vwr_frame


class slice_viewer_frame(wxFrame):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

# end of class slice_viewer_frame


