# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkBYUWriter(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkBYUWriter(), 'Writing vtkBYU.',
            ('vtkBYU',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
