# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkBMPReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkBMPReader(), 'Reading vtkBMP.',
            (), ('vtkBMP',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
