# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkBMPWriter(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkBMPWriter(), 'Writing vtkBMP.',
            ('vtkBMP',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
