# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkCGMWriter(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkCGMWriter(), 'Writing vtkCGM.',
            ('vtkCGM',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
