# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkDEMReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkDEMReader(), 'Reading vtkDEM.',
            (), ('vtkDEM',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
