# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkDataSetReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkDataSetReader(), 'Reading vtkDataSet.',
            (), ('vtkDataSet',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
