# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkDataObjectReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkDataObjectReader(), 'Reading vtkDataObject.',
            (), ('vtkDataObject',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
