# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkDICOMImageReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkDICOMImageReader(), 'Reading vtkDICOMImage.',
            (), ('vtkDICOMImage',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
