# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkEnSightMasterServerReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkEnSightMasterServerReader(), 'Reading vtkEnSightMasterServer.',
            (), ('vtkEnSightMasterServer',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
