# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkEnSight6Reader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkEnSight6Reader(), 'Reading vtkEnSight6.',
            (), ('vtkEnSight6',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
