# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkEnSightGoldBinaryReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkEnSightGoldBinaryReader(), 'Reading vtkEnSightGoldBinary.',
            (), ('vtkEnSightGoldBinary',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
