# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkGaussianCubeReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkGaussianCubeReader(), 'Reading vtkGaussianCube.',
            (), ('vtkGaussianCube',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
