# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkMCubesWriter(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkMCubesWriter(), 'Writing vtkMCubes.',
            ('vtkMCubes',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
