# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkOBJReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkOBJReader(), 'Reading vtkOBJ.',
            (), ('vtkOBJ',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
