# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkPLOT3DReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkPLOT3DReader(), 'Reading vtkPLOT3D.',
            (), ('vtkPLOT3D',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
