# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkPostScriptWriter(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkPostScriptWriter(), 'Writing vtkPostScript.',
            ('vtkPostScript',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
