# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkPNMWriter(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkPNMWriter(), 'Writing vtkPNM.',
            ('vtkPNM',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
