# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkPushImageReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkPushImageReader(), 'Reading vtkPushImage.',
            (), ('vtkPushImage',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
