# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkPushImageFilterSample(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkPushImageFilterSample(), 'Processing.',
            ('Input 1 (vtkImageData)', 'Input 2 (vtkImageData)'), ('vtkImageData',),
            replaceDoc=True,
            inputFunctions=('SetInput1(inputStream)', 'SetInput2(inputStream)'), outputFunctions=None)
