# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkPLYReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkPLYReader(), 'Reading vtkPLY.',
            (), ('vtkPLY',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
