# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkPNGWriter(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkPNGWriter(), 'Writing vtkPNG.',
            ('vtkPNG',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
