# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkStructuredGridWriter(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkStructuredGridWriter(), 'Writing vtkStructuredGrid.',
            ('vtkStructuredGrid',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
