# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkStructuredPointsWriter(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkStructuredPointsWriter(), 'Writing vtkStructuredPoints.',
            ('vtkStructuredPoints',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
