# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkStructuredGridReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkStructuredGridReader(), 'Reading vtkStructuredGrid.',
            (), ('vtkStructuredGrid',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
