# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkTIFFReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkTIFFReader(), 'Reading vtkTIFF.',
            (), ('vtkTIFF',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
