# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkUGFacetReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkUGFacetReader(), 'Reading vtkUGFacet.',
            (), ('vtkUGFacet',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
