# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkVolume16Reader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkVolume16Reader(), 'Reading vtkVolume16.',
            (), ('vtkVolume16',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
