# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkXMLPImageDataWriter(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXMLPImageDataWriter(), 'Writing vtkXMLPImageData.',
            ('vtkXMLPImageData',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
