# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkXMLPUnstructuredGridWriter(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXMLPUnstructuredGridWriter(), 'Writing vtkXMLPUnstructuredGrid.',
            ('vtkXMLPUnstructuredGrid',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
