# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkXYZMolReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXYZMolReader(), 'Reading vtkXYZMol.',
            (), ('vtkXYZMol',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
