# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkXMLRectilinearGridReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXMLRectilinearGridReader(), 'Reading vtkXMLRectilinearGrid.',
            (), ('vtkXMLRectilinearGrid',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
