# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkXMLPImageDataReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXMLPImageDataReader(), 'Reading vtkXMLPImageData.',
            (), ('vtkXMLPImageData',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
