# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkXMLStructuredGridReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXMLStructuredGridReader(), 'Reading vtkXMLStructuredGrid.',
            (), ('vtkXMLStructuredGrid',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
