# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkXMLPStructuredGridWriter(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXMLPStructuredGridWriter(), 'Writing vtkXMLPStructuredGrid.',
            ('vtkXMLPStructuredGrid',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
