# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkXMLPPolyDataWriter(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXMLPPolyDataWriter(), 'Writing vtkXMLPPolyData.',
            ('vtkXMLPPolyData',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
