# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkXMLPStructuredGridReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXMLPStructuredGridReader(), 'Reading vtkXMLPStructuredGrid.',
            (), ('vtkXMLPStructuredGrid',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
