# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkXMLPRectilinearGridReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXMLPRectilinearGridReader(), 'Reading vtkXMLPRectilinearGrid.',
            (), ('vtkXMLPRectilinearGrid',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
