# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkXMLPolyDataReader(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXMLPolyDataReader(), 'Reading vtkXMLPolyData.',
            (), ('vtkXMLPolyData',),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
