# class generated by DeVIDE::createDeVIDEModuleFromVTKObject
from moduleMixins import simpleVTKClassModuleBase
import vtk

class vtkXMLStructuredGridWriter(simpleVTKClassModuleBase):
    def __init__(self, moduleManager):
        simpleVTKClassModuleBase.__init__(
            self, moduleManager,
            vtk.vtkXMLStructuredGridWriter(), 'Writing vtkXMLStructuredGrid.',
            ('vtkXMLStructuredGrid',), (),
            replaceDoc=True,
            inputFunctions=None, outputFunctions=None)
