#!/usr/bin/env python
# generated by wxGlade 0.3.1 on Sat Nov 22 18:46:12 2003

from wxPython.wx import *

class imageStackRDRViewFrame(wxFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: imageStackRDRViewFrame.__init__
        kwds["style"] = wxDEFAULT_FRAME_STYLE
        wxFrame.__init__(self, *args, **kwds)
        self.panel_1 = wxPanel(self, -1)
        self.fileNamesListBox = wxListBox(self.panel_1, -1, choices=["choice 1"])
        self.addButtonId  =  wxNewId()
        self.button_3 = wxButton(self.panel_1, self.addButtonId , "Add")
        self.button_4 = wxButton(self.panel_1, -1, "Remove")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: imageStackRDRViewFrame.__set_properties
        self.SetTitle("frame_1")
        self.fileNamesListBox.SetSize((480, 240))
        self.fileNamesListBox.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: imageStackRDRViewFrame.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_2 = wxBoxSizer(wxVERTICAL)
        sizer_3 = wxBoxSizer(wxVERTICAL)
        sizer_4 = wxBoxSizer(wxHORIZONTAL)
        sizer_5 = wxBoxSizer(wxVERTICAL)
        sizer_4.Add(self.fileNamesListBox, 0, wxRIGHT|wxEXPAND, 4)
        sizer_5.Add(self.button_3, 0, wxBOTTOM, 4)
        sizer_5.Add(self.button_4, 0, 0, 0)
        sizer_4.Add(sizer_5, 1, wxEXPAND, 0)
        sizer_3.Add(sizer_4, 1, wxEXPAND, 0)
        sizer_2.Add(sizer_3, 1, wxALL|wxEXPAND, 7)
        self.panel_1.SetAutoLayout(1)
        self.panel_1.SetSizer(sizer_2)
        sizer_2.Fit(self.panel_1)
        sizer_2.SetSizeHints(self.panel_1)
        sizer_1.Add(self.panel_1, 1, wxEXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class imageStackRDRViewFrame


