#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.6.3 on Sat Feb 09 13:43:04 2008

import wx

# begin wxGlade: extracode
# end wxGlade



class rawVolumeRDRViewFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: rawVolumeRDRViewFrame.__init__
        kwds["style"] = wx.CAPTION|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER
        wx.Frame.__init__(self, *args, **kwds)
        self.viewFramePanel = wx.Panel(self, -1)
        self.label_1_copy_2 = wx.StaticText(self.viewFramePanel, -1, "Filename")
        self.filenameText = wx.TextCtrl(self.viewFramePanel, -1, "")
        self.browseButtonId = wx.NewId()
        self.button_1_copy = wx.Button(self.viewFramePanel, self.browseButtonId, "Browse")
        self.label_3_copy_1 = wx.StaticText(self.viewFramePanel, -1, "Data type")
        self.dataTypeChoice = wx.Choice(self.viewFramePanel, -1, choices=["Dummy 1", "Dummy 2", "Dummy 3", "Dummy 4", "Dummy 5"])
        self.endiannessRadioBox = wx.RadioBox(self.viewFramePanel, -1, "Endianness", choices=["Little (LSB at lowest address)", "Big (MSB at lowest address)"], majorDimension=2, style=wx.RA_SPECIFY_COLS)
        self.label_2 = wx.StaticText(self.viewFramePanel, -1, "Header size (bytes)")
        self.headerSizeText = wx.TextCtrl(self.viewFramePanel, -1, "0")
        self.label_4 = wx.StaticText(self.viewFramePanel, -1, "Extent (x0, x1, y0, y1, z0, z1)")
        self.extentText = wx.TextCtrl(self.viewFramePanel, -1, "")
        self.label_5 = wx.StaticText(self.viewFramePanel, -1, "Spacing (Sx, Sy, Sz)")
        self.spacingText = wx.TextCtrl(self.viewFramePanel, -1, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: rawVolumeRDRViewFrame.__set_properties
        self.SetTitle("Raw Volume Reader")
        self.dataTypeChoice.SetSelection(0)
        self.endiannessRadioBox.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: rawVolumeRDRViewFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(3, 2, 4, 4)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6.Add(self.label_1_copy_2, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 2)
        sizer_6.Add(self.filenameText, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(self.button_1_copy, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(sizer_6, 0, wx.BOTTOM|wx.EXPAND, 4)
        sizer_3.Add(self.label_3_copy_1, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 2)
        sizer_3.Add(self.dataTypeChoice, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(sizer_3, 0, wx.BOTTOM|wx.EXPAND, 4)
        sizer_7.Add(self.endiannessRadioBox, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_7, 0, wx.BOTTOM|wx.EXPAND, 4)
        sizer_5.Add(sizer_2, 1, wx.ALL|wx.EXPAND, 7)
        grid_sizer_1.Add(self.label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.headerSizeText, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_4, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.extentText, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.spacingText, 0, wx.EXPAND, 0)
        grid_sizer_1.AddGrowableCol(1)
        sizer_5.Add(grid_sizer_1, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 7)
        self.viewFramePanel.SetSizer(sizer_5)
        sizer_1.Add(self.viewFramePanel, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class rawVolumeRDRViewFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = rawVolumeRDRViewFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
