#!/usr/bin/env python
# generated by wxGlade 0.2.1 on Mon Mar 10 22:56:38 2003

from wxPython.wx import *

class rawVolumeRDRViewFrame(wxFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: rawVolumeRDRViewFrame.__init__
        kwds["style"] = wxCAPTION|wxMINIMIZE_BOX|wxMAXIMIZE_BOX|wxSYSTEM_MENU|wxRESIZE_BORDER
        wxFrame.__init__(self, *args, **kwds)
        self.viewFramePanel = wxPanel(self, -1)
        self.label_1_copy_2 = wxStaticText(self.viewFramePanel, -1, "Filename")
        self.filenameText = wxTextCtrl(self.viewFramePanel, -1, "")
        self.browseButtonId  =  wxNewId()
        self.button_1_copy = wxButton(self.viewFramePanel, self.browseButtonId , "Browse")
        self.label_3_copy_1 = wxStaticText(self.viewFramePanel, -1, "Data type")
        self.dataTypeChoice = wxChoice(self.viewFramePanel, -1, choices=["Dummy 1", "Dummy 2", "Dummy 3", "Dummy 4", "Dummy 5"])
        self.endiannessRadioBox = wxRadioBox(self.viewFramePanel, -1, "Endianness", choices=["Little (LSB at lowest address)", "Big (MSB at lowest address)"], majorDimension=2, style=wxRA_SPECIFY_COLS)
        self.label_2 = wxStaticText(self.viewFramePanel, -1, "Header size (bytes)")
        self.headerSizeText = wxTextCtrl(self.viewFramePanel, -1, "0")
        self.label_4 = wxStaticText(self.viewFramePanel, -1, "Extent (x0, x1, y0, y1, z0, z1)")
        self.extentText = wxTextCtrl(self.viewFramePanel, -1, "")
        self.label_5 = wxStaticText(self.viewFramePanel, -1, "Spacing (Sx, Sy, Sz)")
        self.spacingText = wxTextCtrl(self.viewFramePanel, -1, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: rawVolumeRDRViewFrame.__set_properties
        self.SetTitle("Raw Volume Reader")
        self.dataTypeChoice.SetSelection(0)
        self.endiannessRadioBox.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: rawVolumeRDRViewFrame.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_5 = wxBoxSizer(wxVERTICAL)
        grid_sizer_1 = wxFlexGridSizer(3, 2, 4, 4)
        sizer_2 = wxBoxSizer(wxVERTICAL)
        sizer_7 = wxBoxSizer(wxHORIZONTAL)
        sizer_3 = wxBoxSizer(wxHORIZONTAL)
        sizer_6 = wxBoxSizer(wxHORIZONTAL)
        sizer_6.Add(self.label_1_copy_2, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 2)
        sizer_6.Add(self.filenameText, 1, wxALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(self.button_1_copy, 0, wxALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(sizer_6, 0, wxBOTTOM|wxEXPAND, 4)
        sizer_3.Add(self.label_3_copy_1, 0, wxRIGHT|wxALIGN_CENTER_VERTICAL, 2)
        sizer_3.Add(self.dataTypeChoice, 1, wxALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(sizer_3, 0, wxBOTTOM|wxEXPAND, 4)
        sizer_7.Add(self.endiannessRadioBox, 1, wxEXPAND, 0)
        sizer_2.Add(sizer_7, 0, wxBOTTOM|wxEXPAND, 4)
        sizer_5.Add(sizer_2, 1, wxALL|wxEXPAND, 7)
        grid_sizer_1.Add(self.label_2, 0, wxALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.headerSizeText, 0, wxEXPAND, 0)
        grid_sizer_1.Add(self.label_4, 0, wxALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.extentText, 0, wxEXPAND, 0)
        grid_sizer_1.Add(self.label_5, 0, wxALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.spacingText, 0, wxEXPAND, 0)
        grid_sizer_1.AddGrowableCol(1)
        sizer_5.Add(grid_sizer_1, 0, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND, 7)
        self.viewFramePanel.SetAutoLayout(1)
        self.viewFramePanel.SetSizer(sizer_5)
        sizer_5.Fit(self.viewFramePanel)
        sizer_5.SetSizeHints(self.viewFramePanel)
        sizer_1.Add(self.viewFramePanel, 1, wxEXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class rawVolumeRDRViewFrame


